[api]
api_token = "peinohfugu0zooghaek2Os8oraijeitat6ajoo&gai2tha*ocaida2zooTaa7nou"
groq_api_key = "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"

[database]
DB_USER='admin'
DB_PASSWORD='$PRODNE0!G705T2020252027'
DB_HOST='diagnostico-rr.ci5xtzjh5jeq.us-east-1.rds.amazonaws.com'
DB_PORT=3306
DB_NAME='diagnostico'
